name: molt

on:
  schedule:
    - cron: "0 0 */3 * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  udd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: 2.6.5

      - name: Update dependencies
        run: deno run -A jsr:@molt/cli $(find ./scripts/ -name "*.ts") --write

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          commit-message: "Update deno dependencies"
          title: "Update Deno dependencies"
          body: >
            Automated updates by [@molt/cli](https://github.com/hasundue/molt)
            and [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action
          branch: update-deno-dependencies
          author: GitHub <noreply@github.com>
          delete-branch: true
